# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pi Chapter of Phi Gamma Delta

description: >- # this means to ignore newlines until "tagline:"
  Allegheny College Phi Gamma Delta

# tagline: Allegheny College Phi Gamma Delta

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alleghenyfiji.org" # the base hostname & protocol for your site, e.g. http://example.com

email: fiji@allegheny.edu

twitter_page: fiji_pi_chapter
facebook_page: allegheny.fiji
instagram_page: allegheny_fiji

# Build settings
theme: minima

listed_pages:
 - name: Home
   type: page
   url: /
 - name: About
   type: page
   url: /about.html
 - name: Brothers
   type: dropdown
   url: /brothers.html
   subpage:
     - name: Cabinet
       type: page
       url: /cabinet.html
 - name: Graduates
   type: dropdown
   url:
   subpage:
     - name: Pig Dinner
       type: page
       url: /pig_dinner.html
     - name: Donate
       type: page
       url: /donate.html
 - name: Contact
   type: page
   url: /contact.html

misson_statement: >-
  We the brothers of the Pi Chapter of Phi Gamma Delta, exist to create a group
  of extraordinary gentlemen through diversity, excellence, and love for oneself.
  We aim to seek the highest standard of Friendship through diverse lifelong
  bonds of brotherhood. We aim to achieve true Knowledge through scholarly
  excellence. We aim to be the standard of Service for fraternities and
  sororities on campus through our commitment to philanthropy and community
  service. We aim to be the definition of Morality for knowing right from wrong
  and treating others with the utmost respect and showing we are truly Fiji
  gentlemen. We aim to achieve Excellence by upholding these four values and
  will aim to always lead with love and compassion for oneself and for the world.

Pig_Gig:
  - date: "Saturday March 28th, 2020"
    gig_time: "3:00 PM - 8:00PM"
    location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2979.3611926473545!2d-80.12892324957828!3d41.69113778497157!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8832585f6d68870f%3A0xa9dfc771e68c1927!2sThe%20Country%20Club%20of%20Meadville!5e0!3m2!1sen!2sus!4v1581033651910!5m2!1sen!2sus"

plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
