apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: pi
spec:
  selector:
    app: api-deploy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30800
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: pi
spec:
  selector:
    matchLabels:
      app: api-deploy
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
        - name: api-deploy
          image: pi-api:1.0.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # ports:
          # - containerPort: 8080
